### ISSUE TITLE
serializer to use predefined namespace prefixes

### ISSUE THREAD

**Issue by zhiboz** [cosminbasca/surfrdf#12]
```
graph = store.reader.graph
print graph.serialize(format='n3')
```
yields something like

`@prefix ns2: <http://xmlns.com/foaf/0.1/> .`

where `ns2` is used instead of the predefined namespace prefix `foaf:`. tried different serialization formats with no luck.

is it possible to ask surf to use the predefined namespace prefixes in serialization? thanks!

**Comment by cosminbasca** [comment]
Hi @zhiboz thanks for pointing this one out. In general the *rdflib* graph.serialize method does not support this functionality, but there is a workaround which I can implemented in the *surf* resource.serialize, I am somewhat busy atm but will get to it soon.

**Comment by zhiboz** [comment]
this works!

```
g = store.reader.graph
# Bind a few prefix, namespace pairs for more readable output
g.bind("dc", ns.DC)
g.bind("foaf", ns.FOAF)
print g.serialize(format='n3')
```

**Comment by cosminbasca** [comment]
Hi @zhiboz, thanks for the feedback. As a convenience surf should probably bind the inner namespaces when calling serialize. I will have a look into it when I get some spare time
