### ISSUE TITLE
pip install fails - can not find SuRF distribution

### ISSUE THREAD

**Issue by CaptSolo** [cosminbasca/surfrdf#3]
pip install fails - unable to find a suitable SuRF package on PyPi:
```
pip install --upgrade SuRF
Collecting SuRF
  Could not find a version that satisfies the requirement SuRF (from versions: )
No matching distribution found for SuRF
```
environment: Python 2.7 on Mac OS X 10.9.5 (the error does not seem to be Mac-specific though).

**Comment by CaptSolo** [comment]
Verbose logs show that pip is looking through a number of .egg files but does not like them for some reason:

```
    [...]
    Skipping link https://pypi.python.org/packages/2.7/S/SuRF/SuRF-1.1.3_r281-py2.7.egg#md5=400736cdab8597929dd8e6060129a517 (from https://pypi.python.org/simple/surf/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/S/SuRF/SuRF-1.1.3_r294-py2.7.egg#md5=fc0384619219a1761b74c357098317b1 (from https://pypi.python.org/simple/surf/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/S/SuRF/SuRF-1.1.4_r352-py2.7.egg#md5=c913dbcab1546c723269dcfc54da7938 (from https://pypi.python.org/simple/surf/); unsupported archive format: .egg
  Could not find a version that satisfies the requirement SuRF (from versions: )
Cleaning up...
No matching distribution found for SuRF
```

**Comment by CaptSolo** [comment]
Install from Github works OK:
`pip install git+https://github.com/cosminbasca/surfrdf`

However, SuRF plugins also need to be installed and I don't know if / how they can be installed this way.

**Comment by cosminbasca** [comment]
I will have to give it a look as soon as I get some spare time :), thanks for the heads up Uldis!

**Comment by mromanello** [comment]
Hi @cosminbasca ! I've come across the same issue. It's due to the fact that surf's version number was recently changed to `0.1.8`. Plus there is one small change needed (removal of an import statement) in the SPARQL plugin. I've made these changes locally and got it work fine: should I open a pull request?

**Comment by cosminbasca** [comment]
@CaptSolo  @mromanello surf 1.1.9 just around the corner, this is a transitional version towards 2.x. 
A few changes starting with 1.1.9
- dropped support for legacy rdflib (4.x support only)
- rdflib and sparql_protocol plugins are bundled by default (batteries included)

Cheers,
Cosmin

**Comment by cosminbasca** [comment]
version 1.1.9 is on pypi.
